// When the factButton is clicked...
$("#factButton").on("click", function() {
    // We generate a random number between 0 and 7 (the number of facts in the silkieFactArray)
    var number = Math.floor((Math.random() * silkieFactArray.length));
    // We display the fact from the silkieFactArray that is in the random position we just generated.
    $("#factText").html(silkieFactArray[number])
})

// This array holds all of our Silkie facts!
var silkieFactArray = ["<h3>SILKIE CHICKENS ARE FLUFFY</h3> <br> The feathers on these birds are furry and fluffy because they don’t have barbs to hold them down. Instead each individual Silkie feather flutters and flies around her like a walking feather duster. This can cause Silkies to get extra cold in the winter, but our Mokey has never had a problem, even in -5˚F without heat in the coop.", "<h3>SILKIE CHICKENS HAVE BLACK SKIN AND BONES</h3><br>Besides the silly fur-like feathers that make a Silkie look like a Muppet, these birds have several other weirdo traits that make them stand out. Silkie’s skin is black or dark blue instead of white. They also have black bones. These are two very strange traits that they share with a few other chicken breeds, the Ayam Cemani among them.", "<h3>SILKIES HAVE EXTRA TOES</h3><br>Silkies have five toes on their feet instead of the usual four. The fifth toe is very small and pokes out between two others, like it just mistakenly sprouted there one day and decided to hang around. Even with the extra toe (or perhaps because of it) our Silkie, Mokey is a clumsy lady. Whenever another chicken chases her she does this hysterical hop sprint while flapping her wings and trying to stay upright. I laugh every time I see it.", "<h3>SILKIE CHICKENS’ EARS ARE TURQUOISE</h3><br>The earlobes of these birds are what truly make them stand out. We thought something was wrong with our Silkie rooster when we noticed his ears were turning blue. In fact, they were bright turquoise! “How interesting!” we said. “How creepy!” we thought. When his comb and wattles started coming in purplish maroon, I was sure we had some kind of circus freak on our hands. Turns out, that’s just Silkies for ya.", "<h3>SILKIES MAKE GOOD PETS</h3><br>Because of the docile nature of these birds and the fact that they don’t make much noise and can barely fly, many people keep them as pets. They are very sweet and love to be held and pet. I’ve seen Silkies that crave the attention of their owners and will sit on their lap all day long. Because of these qualities, they are also the most recommended chicken breed for children.", "<h3>SILKIE CHICKENS ARE A DELICACY</h3><br>Many people consider Silkie chicken meat to be a delicacy, and restaurants like to charge a pretty penny because of it. Many cultures also believe Silkie meat to have healing properties and contain more nutrients than traditional chicken meat. In China, where Silkies were first bred, women eat these birds after giving birth to get their strength back.", "<h3>SILKIES ARE THE BEST MOTHERS IN THE CHICKEN WORLD</h3><br>It’s no secret that Silkies make wonderful mothers. Their tendency to go broody (have the urge to sit on eggs) is much higher than any other breed. They will patiently incubate those eggs and lovingly care for whatever comes out of them. They will proudly raise the babies of uninterested flock mates. Even baby ducks and turkeys!"]